type CheckoutCopy = {
  shippingCountry: string; selectDestination: string; calculatingShipping: string;
  onlineShippingUnavailable: string; shippingQuoteUnavailable: string; dutiesIncluded: string; dutiesRecipient: string;
  card: string; stripeSecure: string; paypalSeller: string; stripeSeller: string; sellerNotice: string;
  loadingPrice: string; payWithPaypal: string; selectCountry: string;
  paymentSuccess: string; paymentSuccessDetail: string; paymentFailed: string; tryAgain: string;
  totalAmount: string; processingPayment: string; createOrderFailed: string; captureFailed: string; cancelled: string;
  stripeOpen: string; stripePay: string; stripePowered: string; stripeFailed: string;
};

const en: CheckoutCopy = {
  shippingCountry: 'Shipping country', selectDestination: 'Select destination', calculatingShipping: 'Calculating shipping…', onlineShippingUnavailable: 'Online shipping is unavailable. Please request a quote.', shippingQuoteUnavailable: 'Shipping quote unavailable', dutiesIncluded: 'duties included', dutiesRecipient: 'duties paid by recipient', card: 'Credit or debit card', stripeSecure: 'Secure checkout with Stripe', paypalSeller: 'PayPal payments are collected by Quanzhou Reach Technology Co., Ltd.', stripeSeller: 'Card payments through Stripe are collected by HK REACH SOURCING LIMITED.', sellerNotice: 'The applicable seller is also identified on the order confirmation and invoice.', loadingPrice: 'Loading verified product price…', payWithPaypal: 'or pay with PayPal', selectCountry: 'Select country', paymentSuccess: 'Payment successful', paymentSuccessDetail: 'Your payment was captured. We are preparing the order details.', paymentFailed: 'Payment failed', tryAgain: 'Try again', totalAmount: 'Total amount', processingPayment: 'Processing payment…', createOrderFailed: 'Failed to create order', captureFailed: 'Failed to capture payment', cancelled: 'Payment was cancelled or failed. Please try again.', stripeOpen: 'Opening secure checkout…', stripePay: 'Pay securely by card', stripePowered: 'Secure payment powered by Stripe', stripeFailed: 'Unable to start card checkout',
};

const copies: Record<string, CheckoutCopy> = {
  en,
  zh: { ...en, shippingCountry: '收货国家或地区', selectDestination: '请选择目的地', calculatingShipping: '正在计算运费…', onlineShippingUnavailable: '暂不支持在线计算运费，请提交询价。', shippingQuoteUnavailable: '无法获取运费报价', dutiesIncluded: '已包含关税', dutiesRecipient: '关税由收件人支付', card: '信用卡或借记卡', stripeSecure: '通过 Stripe 安全结账', paypalSeller: 'PayPal 款项由 Quanzhou Reach Technology Co., Ltd. 收取。', stripeSeller: 'Stripe 银行卡款项由 HK REACH SOURCING LIMITED 收取。', sellerNotice: '适用的销售主体也会列在订单确认和发票中。', loadingPrice: '正在加载已核实的产品价格…', payWithPaypal: '或使用 PayPal 付款', selectCountry: '请选择国家或地区', paymentSuccess: '付款成功', paymentSuccessDetail: '付款已完成，我们正在准备订单详情。', paymentFailed: '付款失败', tryAgain: '重试', totalAmount: '付款总额', processingPayment: '正在处理付款…', createOrderFailed: '无法创建订单', captureFailed: '无法完成付款', cancelled: '付款已取消或失败，请重试。', stripeOpen: '正在打开安全结账…', stripePay: '使用银行卡安全付款', stripePowered: '由 Stripe 提供安全支付服务', stripeFailed: '无法启动银行卡结账' },
  es: { ...en, shippingCountry: 'País de entrega', selectDestination: 'Seleccione el destino', calculatingShipping: 'Calculando el envío…', onlineShippingUnavailable: 'El envío en línea no está disponible. Solicite una cotización.', shippingQuoteUnavailable: 'Cotización de envío no disponible', dutiesIncluded: 'aranceles incluidos', dutiesRecipient: 'aranceles a cargo del destinatario', card: 'Tarjeta de crédito o débito', stripeSecure: 'Pago seguro con Stripe', paypalSeller: 'Los pagos de PayPal los cobra Quanzhou Reach Technology Co., Ltd.', stripeSeller: 'Los pagos con tarjeta mediante Stripe los cobra HK REACH SOURCING LIMITED.', sellerNotice: 'El vendedor aplicable también figura en la confirmación y la factura.', loadingPrice: 'Cargando el precio verificado…', payWithPaypal: 'o pague con PayPal', selectCountry: 'Seleccione el país', paymentSuccess: 'Pago realizado', paymentSuccessDetail: 'El pago se capturó y estamos preparando los datos del pedido.', paymentFailed: 'Error de pago', tryAgain: 'Intentar de nuevo', totalAmount: 'Importe total', processingPayment: 'Procesando el pago…', createOrderFailed: 'No se pudo crear el pedido', captureFailed: 'No se pudo capturar el pago', cancelled: 'El pago se canceló o falló. Inténtelo de nuevo.', stripeOpen: 'Abriendo el pago seguro…', stripePay: 'Pagar de forma segura con tarjeta', stripePowered: 'Pago seguro proporcionado por Stripe', stripeFailed: 'No se pudo iniciar el pago con tarjeta' },
  ru: { ...en, shippingCountry: 'Страна доставки', selectDestination: 'Выберите страну', calculatingShipping: 'Расчет доставки…', onlineShippingUnavailable: 'Онлайн-доставка недоступна. Запросите расчет.', shippingQuoteUnavailable: 'Расчет доставки недоступен', dutiesIncluded: 'пошлины включены', dutiesRecipient: 'пошлины оплачивает получатель', card: 'Кредитная или дебетовая карта', stripeSecure: 'Безопасное оформление через Stripe', paypalSeller: 'Платежи PayPal получает Quanzhou Reach Technology Co., Ltd.', stripeSeller: 'Платежи картой через Stripe получает HK REACH SOURCING LIMITED.', sellerNotice: 'Применимый продавец также указан в подтверждении заказа и счете.', loadingPrice: 'Загрузка проверенной цены…', payWithPaypal: 'или оплатите через PayPal', selectCountry: 'Выберите страну', paymentSuccess: 'Оплата прошла успешно', paymentSuccessDetail: 'Платеж принят, мы готовим сведения о заказе.', paymentFailed: 'Ошибка оплаты', tryAgain: 'Повторить', totalAmount: 'Итоговая сумма', processingPayment: 'Обработка платежа…', createOrderFailed: 'Не удалось создать заказ', captureFailed: 'Не удалось принять платеж', cancelled: 'Платеж отменен или не выполнен. Повторите попытку.', stripeOpen: 'Открытие безопасной оплаты…', stripePay: 'Безопасно оплатить картой', stripePowered: 'Безопасная оплата через Stripe', stripeFailed: 'Не удалось начать оплату картой' },
  ar: { ...en, shippingCountry: 'دولة التسليم', selectDestination: 'اختر الوجهة', calculatingShipping: 'جارٍ حساب الشحن…', onlineShippingUnavailable: 'الشحن عبر الإنترنت غير متاح. اطلب عرضاً.', shippingQuoteUnavailable: 'عرض الشحن غير متاح', dutiesIncluded: 'الرسوم الجمركية مشمولة', dutiesRecipient: 'الرسوم الجمركية يدفعها المستلم', card: 'بطاقة ائتمان أو خصم', stripeSecure: 'إتمام آمن عبر Stripe', paypalSeller: 'تحصل Quanzhou Reach Technology Co., Ltd. مدفوعات PayPal.', stripeSeller: 'تحصل HK REACH SOURCING LIMITED مدفوعات البطاقات عبر Stripe.', sellerNotice: 'تظهر جهة البيع المعنية أيضاً في تأكيد الطلب والفاتورة.', loadingPrice: 'جارٍ تحميل سعر المنتج الموثق…', payWithPaypal: 'أو ادفع عبر PayPal', selectCountry: 'اختر الدولة', paymentSuccess: 'تم الدفع بنجاح', paymentSuccessDetail: 'تم تحصيل الدفع ونعمل على إعداد تفاصيل الطلب.', paymentFailed: 'فشل الدفع', tryAgain: 'حاول مجدداً', totalAmount: 'المبلغ الإجمالي', processingPayment: 'جارٍ معالجة الدفع…', createOrderFailed: 'تعذر إنشاء الطلب', captureFailed: 'تعذر تحصيل الدفع', cancelled: 'أُلغي الدفع أو فشل. حاول مجدداً.', stripeOpen: 'جارٍ فتح الدفع الآمن…', stripePay: 'ادفع بالبطاقة بأمان', stripePowered: 'دفع آمن عبر Stripe', stripeFailed: 'تعذر بدء الدفع بالبطاقة' },
};

export function getCheckoutCopy(locale: string) { return copies[locale] || en; }
