export type RFQCopy = {
  title: string; close: string; brand: string; startingFrom: string;
  quantity: string; quantityPlaceholder: string; targetPrice: string; targetPricePlaceholder: string;
  intendedUse: string; selectIntendedUse: string; companyInfo: string; companyName: string;
  companyNamePlaceholder: string; contactName: string; contactNamePlaceholder: string;
  country: string; selectCountry: string; email: string; phone: string; whatsapp: string;
  message: string; messagePlaceholder: string; marketing: string; submit: string; submitting: string;
  or: string; whatsappInstead: string; submitFailed: string;
  errors: { company: string; contact: string; country: string; emailRequired: string; emailInvalid: string; phone: string; quantity: string; intendedUse: string };
  uses: string[];
  success: { title: string; thanks: string; summary: string; product: string; quantity: string; company: string; country: string; reference: string; followUp: string; close: string; emailSent?: string };
};

const en: RFQCopy = {
  title: 'Request a bulk quote', close: 'Close', brand: 'Brand', startingFrom: 'Starting from', quantity: 'Quantity', quantityPlaceholder: 'Enter quantity', targetPrice: 'Target price per unit (optional)', targetPricePlaceholder: 'Your target price', intendedUse: 'Intended use', selectIntendedUse: 'Select intended use', companyInfo: 'Company information', companyName: 'Company name', companyNamePlaceholder: 'Your company name', contactName: 'Contact name', contactNamePlaceholder: 'Your full name', country: 'Country or region', selectCountry: 'Select your country or region', email: 'Email', phone: 'Phone', whatsapp: 'WhatsApp (optional)', message: 'Additional message (optional)', messagePlaceholder: 'Product, configuration, packaging, destination, or timing requirements', marketing: 'I agree to receive product updates and promotional offers from REACH PROJECTOR.', submit: 'Submit quote request', submitting: 'Submitting…', or: 'or', whatsappInstead: 'Chat on WhatsApp instead', submitFailed: 'Something went wrong. Please try again or contact us through WhatsApp.',
  errors: { company: 'Company name is required', contact: 'Contact name is required', country: 'Please select your country or region', emailRequired: 'Email is required', emailInvalid: 'Please enter a valid email', phone: 'Phone or WhatsApp is required', quantity: 'Quantity must be at least 1', intendedUse: 'Please select the intended use' },
  uses: ['Retail resale', 'Online store', 'Corporate procurement', 'Government or education', 'Distribution or wholesale', 'Project installation', 'Personal use', 'Other'],
  success: { title: 'Quote request received', thanks: 'Thank you, {name}. Our team will review your request and respond with the next steps.', summary: 'Inquiry summary', product: 'Product', quantity: 'Quantity', company: 'Company', country: 'Country or region', reference: 'Reference', followUp: 'Follow up on WhatsApp', close: 'Close' },
};

const copies: Record<string, RFQCopy> = {
  en,
  zh: { ...en, title: '申请批量报价', close: '关闭', brand: '品牌', startingFrom: '起价', quantity: '数量', quantityPlaceholder: '请输入数量', targetPrice: '目标单价（选填）', targetPricePlaceholder: '您的目标价格', intendedUse: '采购用途', selectIntendedUse: '请选择采购用途', companyInfo: '公司信息', companyName: '公司名称', companyNamePlaceholder: '请输入公司名称', contactName: '联系人', contactNamePlaceholder: '请输入姓名', country: '国家或地区', selectCountry: '请选择国家或地区', email: '邮箱', phone: '电话', whatsapp: 'WhatsApp（选填）', message: '补充说明（选填）', messagePlaceholder: '产品、配置、包装、目的地或时间要求', marketing: '我同意接收 REACH PROJECTOR 的产品更新与推广信息。', submit: '提交报价申请', submitting: '正在提交…', or: '或', whatsappInstead: '改用 WhatsApp 沟通', submitFailed: '提交失败，请重试或通过 WhatsApp 联系我们。', errors: { company: '请填写公司名称', contact: '请填写联系人姓名', country: '请选择国家或地区', emailRequired: '请填写邮箱', emailInvalid: '请输入有效邮箱', phone: '请填写电话或 WhatsApp', quantity: '数量至少为 1', intendedUse: '请选择采购用途' }, uses: ['零售转售', '线上商店', '企业采购', '政府或教育', '分销或批发', '项目安装', '个人使用', '其他'], success: { title: '报价申请已收到', thanks: '感谢您，{name}。我们的团队将审核需求并回复后续步骤。', summary: '询价摘要', product: '产品', quantity: '数量', company: '公司', country: '国家或地区', reference: '参考编号', followUp: '通过 WhatsApp 跟进', close: '关闭', emailSent: '确认邮件已发送至 {email}' } },
  es: { ...en, title: 'Solicitar cotización por volumen', close: 'Cerrar', brand: 'Marca', startingFrom: 'Desde', quantity: 'Cantidad', quantityPlaceholder: 'Ingrese la cantidad', targetPrice: 'Precio objetivo por unidad (opcional)', targetPricePlaceholder: 'Su precio objetivo', intendedUse: 'Uso previsto', selectIntendedUse: 'Seleccione el uso previsto', companyInfo: 'Información de la empresa', companyName: 'Empresa', companyNamePlaceholder: 'Nombre de la empresa', contactName: 'Persona de contacto', contactNamePlaceholder: 'Nombre completo', country: 'País o región', selectCountry: 'Seleccione su país o región', email: 'Correo electrónico', phone: 'Teléfono', whatsapp: 'WhatsApp (opcional)', message: 'Mensaje adicional (opcional)', messagePlaceholder: 'Producto, configuración, embalaje, destino o plazo', marketing: 'Acepto recibir novedades y ofertas de REACH PROJECTOR.', submit: 'Enviar solicitud', submitting: 'Enviando…', or: 'o', whatsappInstead: 'Hablar por WhatsApp', submitFailed: 'No se pudo enviar. Inténtelo de nuevo o contáctenos por WhatsApp.', errors: { company: 'La empresa es obligatoria', contact: 'El contacto es obligatorio', country: 'Seleccione su país o región', emailRequired: 'El correo es obligatorio', emailInvalid: 'Ingrese un correo válido', phone: 'Se requiere teléfono o WhatsApp', quantity: 'La cantidad mínima es 1', intendedUse: 'Seleccione el uso previsto' }, uses: ['Reventa minorista', 'Tienda en línea', 'Compra corporativa', 'Gobierno o educación', 'Distribución o mayorista', 'Instalación de proyectos', 'Uso personal', 'Otro'], success: { title: 'Solicitud recibida', thanks: 'Gracias, {name}. Revisaremos su solicitud y responderemos con los próximos pasos.', summary: 'Resumen de la consulta', product: 'Producto', quantity: 'Cantidad', company: 'Empresa', country: 'País o región', reference: 'Referencia', followUp: 'Continuar por WhatsApp', close: 'Cerrar', emailSent: 'Se envió una confirmación a {email}' } },
  ru: { ...en, title: 'Запросить оптовый расчет', close: 'Закрыть', brand: 'Бренд', startingFrom: 'Цена от', quantity: 'Количество', quantityPlaceholder: 'Введите количество', targetPrice: 'Целевая цена за единицу (необязательно)', targetPricePlaceholder: 'Ваша целевая цена', intendedUse: 'Назначение', selectIntendedUse: 'Выберите назначение', companyInfo: 'Информация о компании', companyName: 'Компания', companyNamePlaceholder: 'Название компании', contactName: 'Контактное лицо', contactNamePlaceholder: 'Ваше имя', country: 'Страна или регион', selectCountry: 'Выберите страну или регион', email: 'Эл. почта', phone: 'Телефон', whatsapp: 'WhatsApp (необязательно)', message: 'Дополнительное сообщение', messagePlaceholder: 'Товар, конфигурация, упаковка, страна или сроки', marketing: 'Я согласен получать новости и предложения REACH PROJECTOR.', submit: 'Отправить запрос', submitting: 'Отправка…', or: 'или', whatsappInstead: 'Написать в WhatsApp', submitFailed: 'Не удалось отправить. Повторите попытку или свяжитесь с нами через WhatsApp.', errors: { company: 'Укажите компанию', contact: 'Укажите контактное лицо', country: 'Выберите страну или регион', emailRequired: 'Укажите эл. почту', emailInvalid: 'Введите корректный адрес', phone: 'Укажите телефон или WhatsApp', quantity: 'Минимальное количество — 1', intendedUse: 'Выберите назначение' }, uses: ['Розничная перепродажа', 'Интернет-магазин', 'Корпоративная закупка', 'Государство или образование', 'Дистрибуция или опт', 'Проектный монтаж', 'Личное использование', 'Другое'], success: { title: 'Запрос получен', thanks: 'Спасибо, {name}. Мы изучим запрос и сообщим следующие шаги.', summary: 'Сводка запроса', product: 'Товар', quantity: 'Количество', company: 'Компания', country: 'Страна или регион', reference: 'Номер', followUp: 'Продолжить в WhatsApp', close: 'Закрыть', emailSent: 'Подтверждение отправлено на {email}' } },
  ar: { ...en, title: 'طلب عرض أسعار بالجملة', close: 'إغلاق', brand: 'العلامة', startingFrom: 'يبدأ من', quantity: 'الكمية', quantityPlaceholder: 'أدخل الكمية', targetPrice: 'السعر المستهدف للوحدة (اختياري)', targetPricePlaceholder: 'السعر المستهدف', intendedUse: 'الاستخدام المقصود', selectIntendedUse: 'اختر الاستخدام', companyInfo: 'معلومات الشركة', companyName: 'اسم الشركة', companyNamePlaceholder: 'أدخل اسم الشركة', contactName: 'اسم جهة الاتصال', contactNamePlaceholder: 'أدخل الاسم الكامل', country: 'الدولة أو المنطقة', selectCountry: 'اختر الدولة أو المنطقة', email: 'البريد الإلكتروني', phone: 'الهاتف', whatsapp: 'WhatsApp (اختياري)', message: 'رسالة إضافية (اختياري)', messagePlaceholder: 'المنتج أو الإعداد أو التغليف أو الوجهة أو الموعد', marketing: 'أوافق على تلقي تحديثات وعروض REACH PROJECTOR.', submit: 'إرسال طلب العرض', submitting: 'جارٍ الإرسال…', or: 'أو', whatsappInstead: 'تواصل عبر WhatsApp', submitFailed: 'تعذر الإرسال. حاول مجدداً أو تواصل معنا عبر WhatsApp.', errors: { company: 'اسم الشركة مطلوب', contact: 'اسم جهة الاتصال مطلوب', country: 'اختر الدولة أو المنطقة', emailRequired: 'البريد الإلكتروني مطلوب', emailInvalid: 'أدخل بريداً صحيحاً', phone: 'الهاتف أو WhatsApp مطلوب', quantity: 'الحد الأدنى للكمية هو 1', intendedUse: 'اختر الاستخدام المقصود' }, uses: ['إعادة البيع', 'متجر إلكتروني', 'شراء للشركات', 'حكومة أو تعليم', 'توزيع أو جملة', 'تركيب مشروع', 'استخدام شخصي', 'أخرى'], success: { title: 'تم استلام الطلب', thanks: 'شكراً، {name}. سيراجع فريقنا طلبك ويرسل الخطوات التالية.', summary: 'ملخص الاستفسار', product: 'المنتج', quantity: 'الكمية', company: 'الشركة', country: 'الدولة أو المنطقة', reference: 'المرجع', followUp: 'المتابعة عبر WhatsApp', close: 'إغلاق', emailSent: 'تم إرسال التأكيد إلى {email}' } },
};

export function getRFQCopy(locale: string) { return copies[locale] || en; }
