import { getSupabaseClient } from '@/storage/database/supabase-client';

const client = getSupabaseClient();

const categories = [
  { name: 'Projectors', slug: 'projectors', description: 'Professional 4K Laser Projectors, UST Laser TVs and home theater solutions from top brands.', image_url: '/images/category-projectors.jpg', sort_order: 1 },
  { name: 'Printers', slug: 'printers', description: 'High-performance laser and inkjet printers for office and home use.', image_url: '/images/category-printers.jpg', sort_order: 2 },
  { name: 'Components', slug: 'components', description: 'Premium PC components including CPUs, GPUs, motherboards, memory and storage.', image_url: '/images/category-components.jpg', sort_order: 3 },
];

const subcategories: Record<string, string[]> = {
  projectors: ['4K Laser Projectors', 'UST Laser TV', 'Portable Projectors'],
  printers: ['Laser Printers', 'Inkjet Printers', 'Multifunction Printers'],
  components: ['CPUs', 'GPUs', 'Motherboards', 'Memory', 'Storage'],
};

const products = [
  // Projectors
  { name: 'JMGO N5S ULTRA MAX 4K', slug: 'jmgo-n5s-ultra-max-4k', brand: 'JMGO', category: 'projectors', price: 1600, short_description: 'Premium 4K laser projector with exceptional brightness and color accuracy for home theater.', description: 'The JMGO N5S ULTRA MAX 4K delivers an immersive cinematic experience with its advanced laser light source, delivering stunning 4K resolution with vivid colors and deep contrasts. Perfect for dedicated home theater setups.', features: ['4K UHD Resolution', 'Laser Light Source', '3000+ ANSI Lumens', 'HDR10+ Support', 'Auto Keystone Correction', 'Built-in Speaker'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '3200 ANSI Lumens', 'Light Source': 'Triple Color Laser', 'Contrast Ratio': '3000:1', 'Throw Ratio': '1.2:1', 'Lens Shift': 'Vertical/Horizontal', 'Speaker': '2 x 10W', 'Weight': '9.5 kg' }, images: ['/images/products/jmgo-n5s.jpg'], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  { name: 'XGIMI RS 10 Ultra 4K', slug: 'xgimi-rs-10-ultra-4k', brand: 'XGIMI', category: 'projectors', price: 2499.99, short_description: 'Flagship 4K laser projector with dual laser engine and Dolby Vision support.', description: 'The XGIMI RS 10 Ultra represents the pinnacle of home projection technology. Featuring a dual laser engine that delivers unparalleled brightness and color volume, with Dolby Vision and HDR10+ for the most lifelike images.', features: ['4K UHD Resolution', 'Dual Laser Engine', '3500+ ANSI Lumens', 'Dolby Vision + HDR10+', 'Auto Focus & Keystone', 'Harman Kardon Speakers'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '3500 ANSI Lumens', 'Light Source': 'Dual Laser', 'Contrast Ratio': '3500:1', 'Throw Ratio': '1.2:1', 'Speaker': '2 x 12W Harman Kardon', 'Connectivity': 'HDMI 2.1 x2, USB 3.0 x2', 'Weight': '10.2 kg' }, images: ['/images/products/xgimi-rs10-ultra.jpg'], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  { name: 'XGIMI RS 10 Mini 4K', slug: 'xgimi-rs-10-mini-4k', brand: 'XGIMI', category: 'projectors', price: 1199.99, short_description: 'Compact 4K laser projector with premium features in a smaller form factor.', description: 'The XGIMI RS 10 Mini 4K brings flagship performance to a compact design. Perfect for smaller rooms while maintaining incredible image quality and smart features.', features: ['4K UHD Resolution', 'Laser Light Source', '2000+ ANSI Lumens', 'HDR10+ Support', 'Smart Auto Adjustment', 'Portable Design'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2000 ANSI Lumens', 'Light Source': 'Laser', 'Contrast Ratio': '2500:1', 'Throw Ratio': '1.2:1', 'Speaker': '2 x 8W', 'Weight': '4.5 kg' }, images: ['/images/products/xgimi-rs10-mini.jpg'], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'Hisense VIDDA C5 Master 4K', slug: 'hisense-vidda-c5-master-4k', brand: 'Hisense', category: 'projectors', price: 2699.99, short_description: 'Professional-grade 4K laser projector with cinema-level color accuracy.', description: 'The Hisense VIDDA C5 Master 4K is engineered for the most demanding home theater enthusiasts. With cinema-grade color accuracy and advanced laser technology, every frame comes alive with breathtaking detail.', features: ['4K UHD Resolution', 'Triple Laser (ALPD 5.0)', '4000+ ANSI Lumens', 'Cinema-grade Color', '120Hz Refresh Rate', 'Advanced Cooling System'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '4200 ANSI Lumens', 'Light Source': 'ALPD 5.0 Triple Laser', 'Color Gamut': '110% BT.2020', 'Throw Ratio': '0.9:1 - 1.5:1', 'Speaker': '2 x 15W', 'Weight': '12.5 kg' }, images: ['/images/products/hisense-vidda-c5.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'Hisense PX2-Pro 4K UST', slug: 'hisense-px2-pro-4k-ust', brand: 'Hisense', category: 'projectors', price: 2399.99, short_description: 'Ultra Short Throw 4K laser TV with 120" image from inches away.', description: 'The Hisense PX2-Pro transforms any wall into a massive 120-inch 4K display from just inches away. Its ultra-short throw design eliminates shadows and glare, delivering a true cinema experience in your living room.', features: ['4K UHD Resolution', 'Ultra Short Throw', '2400+ ANSI Lumens', 'Triple Laser', 'Dolby Vision', 'Ambient Light Rejecting'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2400 ANSI Lumens', 'Light Source': 'Triple Laser', 'Throw Ratio': '0.23:1', 'Screen Size': '80" - 150"', 'Speaker': '2 x 15W + Subwoofer', 'Weight': '14 kg' }, images: ['/images/products/hisense-px2-pro.jpg'], is_featured: true, stock_status: 'in_stock' },
  { name: 'AWOL Vision LTV-3500 4K', slug: 'awol-vision-ltv-3500-4k', brand: 'AWOL Vision', category: 'projectors', price: 5999.99, short_description: 'Premium RGB triple laser UST projector with unmatched brightness.', description: 'The AWOL Vision LTV-3500 is the ultimate ultra-short throw projector featuring an RGB triple laser system that delivers extraordinary brightness and a color volume that surpasses any other projector in its class.', features: ['4K UHD Resolution', 'RGB Triple Laser', '5500+ ANSI Lumens', '150" Display', 'HDR Support', 'Premium Build'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '5500 ANSI Lumens', 'Light Source': 'RGB Triple Laser', 'Throw Ratio': '0.198:1', 'Screen Size': '80" - 150"', 'Speaker': '2 x 15W', 'Weight': '18 kg' }, images: ['/images/products/awol-ltv3500.jpg'], is_featured: true, stock_status: 'in_stock' },
  { name: 'Formovie Theater 4K', slug: 'formovie-theater-4k', brand: 'Formovie', category: 'projectors', price: 3499.99, short_description: 'Award-winning UST laser projector with ALPD 4.5 technology.', description: 'The Formovie Theater combines ALPD 4.5 laser technology with an ultra-short throw design to deliver stunning 4K images. Winner of multiple awards for its exceptional picture quality and value.', features: ['4K UHD Resolution', 'ALPD 4.5 Laser', '2800+ ANSI Lumens', 'Dolby Vision + HDR10+', '150" Screen', 'Android TV Built-in'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2800 ANSI Lumens', 'Light Source': 'ALPD 4.5', 'Throw Ratio': '0.23:1', 'Screen Size': '80" - 150"', 'Speaker': '2 x 15W Dolby Audio', 'Weight': '12 kg' }, images: ['/images/products/formovie-theater.jpg'], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'JMGO U2 4K Laser TV', slug: 'jmgo-u2-4k-laser-tv', brand: 'JMGO', category: 'projectors', price: 2199.99, short_description: 'Sleek 4K laser TV with superior optics and smart features.', description: 'The JMGO U2 brings cinematic 4K quality to your living room with its compact laser TV design. Featuring advanced optics and smart connectivity for effortless entertainment.', features: ['4K UHD Resolution', 'Laser Light Source', '2400 ANSI Lumens', 'HDR10+', 'Auto Focus', 'Smart OS'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2400 ANSI Lumens', 'Light Source': 'Laser', 'Throw Ratio': '0.23:1', 'Screen Size': '80" - 130"', 'Speaker': '2 x 10W', 'Weight': '8.5 kg' }, images: ['/images/products/jmgo-u2.jpg'], stock_status: 'in_stock' },
  { name: 'XGIMI Horizon Ultra', slug: 'xgimi-horizon-ultra', brand: 'XGIMI', category: 'projectors', price: 1799.99, short_description: 'Premium 4K HDR projector with Dolby Vision and hybrid light source.', description: 'The XGIMI Horizon Ultra combines a hybrid light source (LED + Laser) for exceptional brightness and color accuracy. With Dolby Vision support and premium audio, it delivers a complete entertainment experience.', features: ['4K UHD Resolution', 'Hybrid LED+Laser', '2300 ISO Lumens', 'Dolby Vision', 'Harman Kardon Audio', 'Android TV 11'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2300 ISO Lumens', 'Light Source': 'LED + Laser', 'Throw Ratio': '1.2:1', 'Speaker': '2 x 12W Harman Kardon', 'Weight': '5.5 kg' }, images: ['/images/products/xgimi-horizon-ultra.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'XGIMI MoGo 3 Pro', slug: 'xgimi-mogo-3-pro', brand: 'XGIMI', category: 'projectors', price: 599.99, short_description: 'Portable 1080p projector with built-in battery and Android TV.', description: 'Take your entertainment anywhere with the XGIMI MoGo 3 Pro. This portable projector features a built-in battery for cord-free viewing and delivers impressive 1080p image quality.', features: ['1080p Full HD', 'Built-in Battery', '400 ISO Lumens', 'Android TV', 'Auto Keystone', 'Portable Design'], specifications: { 'Resolution': '1920 x 1080', 'Brightness': '400 ISO Lumens', 'Battery Life': '2.5 hours', 'Throw Ratio': '1.1:1', 'Speaker': '2 x 4W', 'Weight': '1.6 kg' }, images: ['/images/products/xgimi-mogo3-pro.jpg'], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'JMGO N1 Ultra 4K', slug: 'jmgo-n1-ultra-4k', brand: 'JMGO', category: 'projectors', price: 1399.99, short_description: 'Compact 4K laser projector with innovative gimbal design.', description: 'The JMGO N1 Ultra features an innovative built-in gimbal stand that allows 360-degree rotation and easy angle adjustment. Combined with 4K laser projection, it offers unmatched versatility.', features: ['4K UHD Resolution', 'Laser Light Source', '2200 ANSI Lumens', '360-degree Gimbal', 'Auto Focus & Keystone', 'Cloud Gaming Ready'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2200 ANSI Lumens', 'Light Source': 'Triple Color Laser', 'Throw Ratio': '0.6:1 - 4.5:1', 'Speaker': '2 x 10W', 'Weight': '4.6 kg' }, images: ['/images/products/jmgo-n1-ultra.jpg'], stock_status: 'in_stock' },
  { name: 'Hisense PL1 4K Laser TV', slug: 'hisense-pl1-4k-laser-tv', brand: 'Hisense', category: 'projectors', price: 1899.99, short_description: 'Affordable 4K UST laser TV with impressive performance.', description: 'The Hisense PL1 offers 4K ultra-short throw projection at an accessible price point. Perfect for those wanting a large-screen experience without the premium price tag.', features: ['4K UHD Resolution', 'Laser Light Source', '2100 ANSI Lumens', 'Ultra Short Throw', 'Smart TV Built-in', 'Voice Control'], specifications: { 'Resolution': '3840 x 2160', 'Brightness': '2100 ANSI Lumens', 'Light Source': 'Laser', 'Throw Ratio': '0.25:1', 'Screen Size': '80" - 120"', 'Speaker': '2 x 10W', 'Weight': '8 kg' }, images: ['/images/products/hisense-pl1.jpg'], stock_status: 'in_stock' },
  // Printers
  { name: 'HP LaserJet Pro M404dn', slug: 'hp-laserjet-pro-m404dn', brand: 'HP', category: 'printers', price: 329, short_description: 'Fast monochrome laser printer for busy offices.', description: 'The HP LaserJet Pro M404dn delivers fast, reliable monochrome printing for busy workgroups. With automatic duplex printing and network connectivity, it handles high-volume office tasks efficiently.', features: ['Monochrome Laser', '40 ppm Print Speed', 'Auto Duplex', 'Network Ready', '250-sheet Tray', 'Low Toner Cost'], specifications: { 'Type': 'Monochrome Laser', 'Speed': '40 ppm', 'Resolution': '1200 x 1200 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB, Ethernet', 'Paper Capacity': '350 sheets', 'Weight': '10.2 kg' }, images: ['/images/products/hp-m404dn.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'Canon imageCLASS LBP226dw', slug: 'canon-imageclass-lbp226dw', brand: 'Canon', category: 'printers', price: 299, short_description: 'Compact wireless monochrome laser printer with duplex printing.', description: 'The Canon imageCLASS LBP226dw combines compact design with powerful performance. Wireless connectivity and automatic duplex printing make it ideal for small offices and home offices.', features: ['Monochrome Laser', '40 ppm Print Speed', 'Wireless + Ethernet', 'Auto Duplex', 'Canon UFR II', 'Energy Efficient'], specifications: { 'Type': 'Monochrome Laser', 'Speed': '40 ppm', 'Resolution': '1200 x 1200 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB, Wi-Fi, Ethernet', 'Weight': '8.4 kg' }, images: ['/images/products/canon-lbp226dw.jpg'], stock_status: 'in_stock' },
  { name: 'Brother HL-L2370DW', slug: 'brother-hl-l2370dw', brand: 'Brother', category: 'printers', price: 209, short_description: 'Reliable wireless monochrome laser printer for home and small office.', description: 'The Brother HL-L2370DW offers reliable, cost-effective monochrome printing with wireless connectivity. Its compact design and fast print speeds make it perfect for home offices.', features: ['Monochrome Laser', '36 ppm Print Speed', 'Wireless Printing', 'Auto Duplex', '250-sheet Tray', 'Mobile Printing'], specifications: { 'Type': 'Monochrome Laser', 'Speed': '36 ppm', 'Resolution': '2400 x 600 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB 2.0, Wi-Fi', 'Weight': '7.2 kg' }, images: ['/images/products/brother-hl-l2370dw.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'Epson EcoTank ET-4850', slug: 'epson-ecotank-et-4850', brand: 'Epson', category: 'printers', price: 449, short_description: 'All-in-one color inkjet with ultra-low cost per page.', description: 'The Epson EcoTank ET-4850 revolutionizes printing with its cartridge-free design. Fill the tanks instead of replacing cartridges and save up to 90% on ink costs.', features: ['Color Inkjet', 'All-in-One', 'Ultra-low Cost Per Page', 'Auto Duplex', 'ADF Scanner', 'Wi-Fi Direct'], specifications: { 'Type': 'Color Inkjet', 'Speed': '15 ppm (black)', 'Resolution': '4800 x 1200 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB, Wi-Fi, Ethernet', 'Weight': '6.8 kg' }, images: ['/images/products/epson-et4850.jpg'], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'HP Color LaserJet Pro M479fdw', slug: 'hp-color-laserjet-pro-m479fdw', brand: 'HP', category: 'printers', price: 549, short_description: 'Multifunction color laser printer with advanced security features.', description: 'The HP Color LaserJet Pro M479fdw delivers professional color printing, scanning, copying, and faxing in one device. Advanced security features protect your business data.', features: ['Color Laser', 'Multifunction', '28 ppm Print Speed', 'Auto Duplex', '50-sheet ADF', 'HP Security Features'], specifications: { 'Type': 'Color Laser', 'Speed': '28 ppm', 'Resolution': '600 x 600 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB, Wi-Fi, Ethernet', 'Weight': '20.3 kg' }, images: ['/images/products/hp-m479fdw.jpg'], stock_status: 'in_stock' },
  { name: 'Canon MAXIFY GX7020', slug: 'canon-maxify-gx7020', brand: 'Canon', category: 'printers', price: 499, short_description: 'High-volume refillable ink tank all-in-one printer.', description: 'The Canon MAXIFY GX7020 is built for high-volume business printing with its refillable ink tank system. Print thousands of pages before refilling, with professional-quality color output.', features: ['Color Inkjet', 'Refillable Ink Tanks', 'All-in-One', '24 ppm Print Speed', 'Auto Duplex', 'Dual Paper Trays'], specifications: { 'Type': 'Color Inkjet', 'Speed': '24 ppm (black)', 'Resolution': '4800 x 1200 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB, Wi-Fi, Ethernet', 'Weight': '11.5 kg' }, images: ['/images/products/canon-gx7020.jpg'], stock_status: 'in_stock' },
  { name: 'Brother MFC-L3770CDW', slug: 'brother-mfc-l3770cdw', brand: 'Brother', category: 'printers', price: 449, short_description: 'Wireless color laser all-in-one with fast duplex printing.', description: 'The Brother MFC-L3770CDW delivers fast color laser printing, scanning, copying, and faxing. Its wireless connectivity and mobile printing capabilities make it perfect for modern offices.', features: ['Color Laser', 'Multifunction', '33 ppm Print Speed', 'Wireless', 'Auto Duplex', '50-sheet ADF'], specifications: { 'Type': 'Color Laser', 'Speed': '33 ppm', 'Resolution': '2400 x 600 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB 3.0, Wi-Fi, Ethernet', 'Weight': '24 kg' }, images: ['/images/products/brother-mfc-l3770cdw.jpg'], stock_status: 'in_stock' },
  { name: 'Epson WorkForce Pro WF-C5790', slug: 'epson-workforce-pro-wf-c5790', brand: 'Epson', category: 'printers', price: 399, short_description: 'Business color inkjet with PrecisionCore technology.', description: 'The Epson WorkForce Pro WF-C5790 uses PrecisionCore heat-free technology for fast, energy-efficient color printing. Replace Pack ink system reduces waste and lowers cost per page.', features: ['Color Inkjet', 'PrecisionCore Technology', '25 ppm Print Speed', 'Replace Pack Ink', 'Auto Duplex', 'Low Energy Use'], specifications: { 'Type': 'Color Inkjet', 'Speed': '25 ppm', 'Resolution': '4800 x 1200 dpi', 'Duplex': 'Automatic', 'Connectivity': 'USB, Wi-Fi, Ethernet, NFC', 'Weight': '16.5 kg' }, images: ['/images/products/epson-wf-c5790.jpg'], stock_status: 'in_stock' },
  // Components - CPUs
  { name: 'Intel Core i9-14900K', slug: 'intel-core-i9-14900k', brand: 'Intel', category: 'components', price: 589, short_description: 'Flagship 24-core desktop processor with 6.0 GHz boost.', description: 'The Intel Core i9-14900K is the ultimate desktop processor with 24 cores (8P + 16E), 32 threads, and boost clocks up to 6.0 GHz. Built on Intel 7 process for exceptional gaming and productivity performance.', features: ['24 Cores / 32 Threads', 'Up to 6.0 GHz', '36MB Intel Smart Cache', 'DDR5 Support', 'PCIe 5.0', 'Intel 7 Process'], specifications: { 'Cores': '24 (8P + 16E)', 'Threads': '32', 'Base Clock': '3.2 GHz (P) / 2.4 GHz (E)', 'Boost Clock': '6.0 GHz', 'Cache': '36 MB', 'TDP': '125W (253W MTP)', 'Socket': 'LGA 1700', 'Memory': 'DDR5-5600 / DDR4-3200' }, images: ['/images/products/intel-i9-14900k.jpg'], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  { name: 'AMD Ryzen 9 7950X', slug: 'amd-ryzen-9-7950x', brand: 'AMD', category: 'components', price: 549, short_description: '16-core Zen 4 processor with exceptional multi-threaded performance.', description: 'The AMD Ryzen 9 7950X delivers 16 cores of Zen 4 performance on the AM5 platform. With boost clocks up to 5.7 GHz and support for DDR5 and PCIe 5.0, it excels at both gaming and content creation.', features: ['16 Cores / 32 Threads', 'Up to 5.7 GHz', '64MB L3 Cache', 'Zen 4 Architecture', 'DDR5 Support', 'PCIe 5.0'], specifications: { 'Cores': '16', 'Threads': '32', 'Base Clock': '4.5 GHz', 'Boost Clock': '5.7 GHz', 'L3 Cache': '64 MB', 'TDP': '170W', 'Socket': 'AM5', 'Memory': 'DDR5-5200' }, images: ['/images/products/amd-ryzen-9-7950x.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'Intel Core i7-14700K', slug: 'intel-core-i7-14700k', brand: 'Intel', category: 'components', price: 409, short_description: 'High-performance 20-core processor for gaming and productivity.', description: 'The Intel Core i7-14700K offers 20 cores (8P + 12E) and 28 threads, delivering excellent performance for gaming, streaming, and content creation at a more accessible price point.', features: ['20 Cores / 28 Threads', 'Up to 5.6 GHz', '33MB Intel Smart Cache', 'DDR5 Support', 'PCIe 5.0', 'Intel 7 Process'], specifications: { 'Cores': '20 (8P + 12E)', 'Threads': '28', 'Base Clock': '3.4 GHz (P) / 2.5 GHz (E)', 'Boost Clock': '5.6 GHz', 'Cache': '33 MB', 'TDP': '125W (253W MTP)', 'Socket': 'LGA 1700', 'Memory': 'DDR5-5600' }, images: ['/images/products/intel-i7-14700k.jpg'], stock_status: 'in_stock' },
  { name: 'AMD Ryzen 7 7800X3D', slug: 'amd-ryzen-7-7800x3d', brand: 'AMD', category: 'components', price: 449, short_description: 'Best gaming CPU with 3D V-Cache technology.', description: 'The AMD Ryzen 7 7800X3D features AMD 3D V-Cache technology with 96MB of L3 cache, making it the ultimate gaming processor. Its 8 cores and 16 threads handle any game with ease.', features: ['8 Cores / 16 Threads', 'Up to 5.0 GHz', '96MB L3 Cache (3D V-Cache)', 'Zen 4 Architecture', 'Best Gaming CPU', 'Low Power 120W TDP'], specifications: { 'Cores': '8', 'Threads': '16', 'Base Clock': '4.2 GHz', 'Boost Clock': '5.0 GHz', 'L3 Cache': '96 MB (3D V-Cache)', 'TDP': '120W', 'Socket': 'AM5', 'Memory': 'DDR5-5200' }, images: ['/images/products/amd-7800x3d.jpg'], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  // Components - GPUs
  { name: 'NVIDIA GeForce RTX 4090', slug: 'nvidia-rtx-4090', brand: 'NVIDIA', category: 'components', price: 1599, short_description: 'Ultimate GPU with Ada Lovelace architecture and 24GB GDDR6X.', description: 'The NVIDIA GeForce RTX 4090 is the most powerful consumer GPU ever made. With 16384 CUDA cores, 24GB GDDR6X memory, and DLSS 3.0, it delivers unprecedented performance for gaming, AI, and content creation.', features: ['16384 CUDA Cores', '24GB GDDR6X', 'DLSS 3.0', 'Ray Tracing Cores', 'Ada Lovelace Architecture', '450W TDP'], specifications: { 'CUDA Cores': '16384', 'Memory': '24 GB GDDR6X', 'Boost Clock': '2520 MHz', 'Memory Bus': '384-bit', 'TDP': '450W', 'Connectors': '1x 16-pin', 'Length': '336 mm' }, images: ['/images/products/nvidia-rtx-4090.jpg'], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  { name: 'MSI GeForce RTX 4080 SUPER', slug: 'msi-rtx-4080-super', brand: 'MSI', category: 'components', price: 999, short_description: 'High-end GPU with 16GB GDDR6X for 4K gaming.', description: 'The MSI GeForce RTX 4080 SUPER delivers exceptional 4K gaming performance with 10240 CUDA cores and 16GB GDDR6X memory. MSI cooling ensures quiet, cool operation under heavy loads.', features: ['10240 CUDA Cores', '16GB GDDR6X', 'DLSS 3.0', 'Ray Tracing', 'MSI Cooling', '4K Gaming Ready'], specifications: { 'CUDA Cores': '10240', 'Memory': '16 GB GDDR6X', 'Boost Clock': '2550 MHz', 'Memory Bus': '256-bit', 'TDP': '320W', 'Connectors': '1x 16-pin', 'Length': '340 mm' }, images: ['/images/products/msi-rtx-4080-super.jpg'], stock_status: 'in_stock' },
  // Components - Memory
  { name: 'Corsair Vengeance DDR5-6000 32GB', slug: 'corsair-vengeance-ddr5-6000-32gb', brand: 'Corsair', category: 'components', price: 119, short_description: 'High-performance DDR5 memory kit optimized for AMD and Intel.', description: 'Corsair Vengeance DDR5-6000 32GB (2x16GB) kit delivers excellent performance for both gaming and productivity. Optimized for AMD EXPO and Intel XMP 3.0 platforms.', features: ['DDR5-6000', '32GB (2x16GB)', 'CL36 Latency', 'Intel XMP 3.0', 'AMD EXPO', 'Aluminum Heat Spreader'], specifications: { 'Type': 'DDR5', 'Speed': '6000 MHz', 'Capacity': '32 GB (2x16GB)', 'Latency': 'CL36-36-36-76', 'Voltage': '1.35V', 'Heat Spreader': 'Aluminum' }, images: ['/images/products/corsair-ddr5-6000.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  // Components - Storage
  { name: 'Samsung 990 Pro 2TB SSD', slug: 'samsung-990-pro-2tb-ssd', brand: 'Samsung', category: 'components', price: 179, short_description: 'PCIe 4.0 NVMe SSD with sequential read up to 7450 MB/s.', description: 'The Samsung 990 Pro 2TB delivers blazing-fast storage performance with sequential reads up to 7450 MB/s. Built on Samsung V-NAND technology and a proprietary controller for maximum reliability.', features: ['PCIe 4.0 NVMe', '2TB Capacity', '7450 MB/s Read', '6900 MB/s Write', 'Samsung V-NAND', '5-Year Warranty'], specifications: { 'Interface': 'PCIe 4.0 x4 NVMe', 'Capacity': '2 TB', 'Sequential Read': '7450 MB/s', 'Sequential Write': '6900 MB/s', 'Random Read': '1400K IOPS', 'Endurance': '1200 TBW', 'Form Factor': 'M.2 2280' }, images: ['/images/products/samsung-990-pro.jpg'], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'WD Black SN850X 2TB SSD', slug: 'wd-black-sn850x-2tb-ssd', brand: 'Western Digital', category: 'components', price: 159, short_description: 'High-performance gaming SSD with up to 7300 MB/s read speed.', description: 'The WD Black SN850X 2TB is engineered for gamers and content creators. With PCIe 4.0 performance and Game Mode 2.0, it delivers the speed and responsiveness needed for modern gaming.', features: ['PCIe 4.0 NVMe', '2TB Capacity', '7300 MB/s Read', 'Game Mode 2.0', 'Predictive Loading', '5-Year Warranty'], specifications: { 'Interface': 'PCIe 4.0 x4 NVMe', 'Capacity': '2 TB', 'Sequential Read': '7300 MB/s', 'Sequential Write': '6600 MB/s', 'Random Read': '1200K IOPS', 'Endurance': '1200 TBW', 'Form Factor': 'M.2 2280' }, images: ['/images/products/wd-sn850x.jpg'], stock_status: 'in_stock' },
  // Components - Motherboards
  { name: 'ASUS ROG Strix Z790-E', slug: 'asus-rog-strix-z790-e', brand: 'ASUS', category: 'components', price: 429, short_description: 'Premium Intel Z790 ATX motherboard with PCIe 5.0 and DDR5.', description: 'The ASUS ROG Strix Z790-E Gaming WiFi is a premium motherboard built for Intel 13th/14th Gen processors. Features PCIe 5.0, DDR5 support, WiFi 6E, and robust power delivery for overclocking.', features: ['Intel Z790 Chipset', 'LGA 1700 Socket', 'DDR5 Support', 'PCIe 5.0 x16', 'WiFi 6E', '20+1 Power Stages'], specifications: { 'Chipset': 'Intel Z790', 'Socket': 'LGA 1700', 'Memory': '4x DDR5 (max 192GB)', 'PCIe': '1x 5.0 x16, 1x 4.0 x4', 'Storage': '5x M.2, 4x SATA', 'Networking': '2.5G LAN + WiFi 6E', 'Form Factor': 'ATX' }, images: ['/images/products/asus-z790-e.jpg'], is_featured: true, stock_status: 'in_stock' },
  { name: 'Gigabyte X670E Aorus Master', slug: 'gigabyte-x670e-aorus-master', brand: 'Gigabyte', category: 'components', price: 499, short_description: 'Premium AMD X670E motherboard with full PCIe 5.0 support.', description: 'The Gigabyte X670E Aorus Master is the ultimate motherboard for AMD Ryzen 7000 series processors. Full PCIe 5.0 support across GPU and M.2 slots, with a massive 18+2+2 power stage design.', features: ['AMD X670E Chipset', 'AM5 Socket', 'DDR5 Support', 'Full PCIe 5.0', 'WiFi 6E', '18+2+2 Power Stages'], specifications: { 'Chipset': 'AMD X670E', 'Socket': 'AM5', 'Memory': '4x DDR5 (max 128GB)', 'PCIe': '1x 5.0 x16, 1x 5.0 M.2', 'Storage': '5x M.2, 4x SATA', 'Networking': '10G LAN + WiFi 6E', 'Form Factor': 'ATX' }, images: ['/images/products/gigabyte-x670e.jpg'], stock_status: 'in_stock' },
];

async function seed() {
  console.log('Seeding database...');

  // Insert categories
  const { data: insertedCategories, error: catError } = await client
    .from('categories')
    .insert(categories)
    .select();
  if (catError) throw new Error(`Failed to insert categories: ${catError.message}`);
  console.log(`Inserted ${insertedCategories.length} categories`);

  // Build category ID map
  const catMap: Record<string, string> = {};
  for (const cat of insertedCategories) {
    catMap[cat.slug] = cat.id;
  }

  // Insert products
  const productRows = products.map((p) => ({
    name: p.name,
    slug: p.slug,
    brand: p.brand,
    category_id: catMap[p.category],
    price: p.price.toString(),
    short_description: p.short_description,
    description: p.description,
    features: p.features || [],
    specifications: p.specifications || {},
    images: p.images || [],
    stock_status: p.stock_status || 'in_stock',
    is_bestseller: p.is_bestseller || false,
    is_new_arrival: p.is_new_arrival || false,
    is_featured: p.is_featured || false,
    is_active: true,
    sort_order: 0,
  }));

  const { data: insertedProducts, error: prodError } = await client
    .from('products')
    .insert(productRows)
    .select();
  if (prodError) throw new Error(`Failed to insert products: ${prodError.message}`);
  console.log(`Inserted ${insertedProducts.length} products`);

  console.log('Seed completed successfully!');
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
