import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Original Supabase credentials (hardcoded for this setup endpoint)
const SUPABASE_URL = 'https://ufzzynacrknnmmyczmzl.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY = 'sb_secret_QNxTm6b3xTUtd9dXB1mteg_ehJmKU-5';

// Categories with specific slugs
const categories = [
  { name: '4K Laser Projectors', slug: '4k-laser-projectors', description: 'Premium 4K laser projectors for home theater and professional use.', image_url: '/images/category-projectors.jpg', sort_order: 1 },
  { name: 'UST Laser TV', slug: 'ust-laser-tv', description: 'Ultra short throw laser TVs with massive screens from inches away.', image_url: '/images/category-ust.jpg', sort_order: 2 },
  { name: 'Projector Mounts', slug: 'projector-mounts', description: 'Professional projector mounts and brackets for ceiling, wall, and floor installations.', image_url: '/images/category-mounts.jpg', sort_order: 3 },
  { name: 'Projection Screens', slug: 'projection-screens', description: 'Premium projection screens including motorized, fixed frame, portable and ALR screens.', image_url: '/images/category-screens.jpg', sort_order: 4 },
];

// Products data
const products = [
  // 4K Laser Projectors
  { name: 'JMGO N5S ULTRA MAX 4K', slug: 'jmgo-n5s-ultra-max-4k', brand: 'JMGO', category_slug: '4k-laser-projectors', price: 1600, short_description: 'Premium 4K laser projector with exceptional brightness and color accuracy.', description: 'The JMGO N5S ULTRA MAX 4K delivers an immersive cinematic experience with its advanced laser light source.', features: ['4K UHD Resolution', 'Laser Light Source', '3000+ ANSI Lumens', 'HDR10+ Support', 'Auto Keystone Correction', 'Built-in Speaker'], specifications: { Resolution: '3840 x 2160', Brightness: '3200 ANSI Lumens', Light_Source: 'Triple Color Laser', Contrast_Ratio: '3000:1', Throw_Ratio: '1.2:1', Speaker: '2 x 10W', Weight: '9.5 kg' }, images: [], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  { name: 'XGIMI RS 10 Ultra 4K', slug: 'xgimi-rs-10-ultra-4k', brand: 'XGIMI', category_slug: '4k-laser-projectors', price: 2499.99, short_description: 'Flagship 4K laser projector with dual laser engine and Dolby Vision.', description: 'The XGIMI RS 10 Ultra represents the pinnacle of home projection technology.', features: ['4K UHD Resolution', 'Dual Laser Engine', '3500+ ANSI Lumens', 'Dolby Vision + HDR10+', 'Auto Focus & Keystone', 'Harman Kardon Speakers'], specifications: { Resolution: '3840 x 2160', Brightness: '3500 ANSI Lumens', Light_Source: 'Dual Laser', Contrast_Ratio: '3500:1', Throw_Ratio: '1.2:1', Speaker: '2 x 12W Harman Kardon', Weight: '10.2 kg' }, images: [], is_bestseller: true, is_featured: true, stock_status: 'in_stock' },
  { name: 'XGIMI RS 10 Mini 4K', slug: 'xgimi-rs-10-mini-4k', brand: 'XGIMI', category_slug: '4k-laser-projectors', price: 1199.99, short_description: 'Compact 4K laser projector with premium features in a smaller form factor.', description: 'The XGIMI RS 10 Mini 4K brings flagship performance to a compact design.', features: ['4K UHD Resolution', 'Laser Light Source', '2000+ ANSI Lumens', 'HDR10+ Support', 'Smart Auto Adjustment', 'Portable Design'], specifications: { Resolution: '3840 x 2160', Brightness: '2000 ANSI Lumens', Light_Source: 'Laser', Contrast_Ratio: '2500:1', Throw_Ratio: '1.2:1', Speaker: '2 x 8W', Weight: '4.5 kg' }, images: [], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'Hisense VIDDA C5 Master 4K', slug: 'hisense-vidda-c5-master-4k', brand: 'Hisense', category_slug: '4k-laser-projectors', price: 2699.99, short_description: 'Professional-grade 4K laser projector with cinema-level color accuracy.', description: 'The Hisense VIDDA C5 Master 4K is engineered for the most demanding home theater enthusiasts.', features: ['4K UHD Resolution', 'Triple Laser (ALPD 5.0)', '4000+ ANSI Lumens', 'Cinema-grade Color', '120Hz Refresh Rate', 'Advanced Cooling System'], specifications: { Resolution: '3840 x 2160', Brightness: '4200 ANSI Lumens', Light_Source: 'ALPD 5.0 Triple Laser', Color_Gamut: '110% BT.2020', Throw_Ratio: '0.9:1 - 1.5:1', Speaker: '2 x 15W', Weight: '12.5 kg' }, images: [], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'XGIMI Horizon Ultra', slug: 'xgimi-horizon-ultra', brand: 'XGIMI', category_slug: '4k-laser-projectors', price: 1799.99, short_description: 'Premium 4K HDR projector with Dolby Vision and hybrid light source.', description: 'The XGIMI Horizon Ultra combines a hybrid light source (LED + Laser) for exceptional brightness.', features: ['4K UHD Resolution', 'Hybrid LED+Laser', '2300 ISO Lumens', 'Dolby Vision', 'Harman Kardon Audio', 'Android TV 11'], specifications: { Resolution: '3840 x 2160', Brightness: '2300 ISO Lumens', Light_Source: 'LED + Laser', Throw_Ratio: '1.2:1', Speaker: '2 x 12W Harman Kardon', Weight: '5.5 kg' }, images: [], is_bestseller: true, stock_status: 'in_stock' },
  { name: 'XGIMI MoGo 3 Pro', slug: 'xgimi-mogo-3-pro', brand: 'XGIMI', category_slug: '4k-laser-projectors', price: 599.99, short_description: 'Portable 1080p projector with built-in battery and Android TV.', description: 'Take your entertainment anywhere with the XGIMI MoGo 3 Pro.', features: ['1080p Full HD', 'Built-in Battery', '400 ISO Lumens', 'Android TV', 'Auto Keystone', 'Portable Design'], specifications: { Resolution: '1920 x 1080', Brightness: '400 ISO Lumens', Battery_Life: '2.5 hours', Throw_Ratio: '1.1:1', Speaker: '2 x 4W', Weight: '1.6 kg' }, images: [], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'JMGO N1 Ultra 4K', slug: 'jmgo-n1-ultra-4k', brand: 'JMGO', category_slug: '4k-laser-projectors', price: 1399.99, short_description: 'Compact 4K laser projector with innovative gimbal design.', description: 'The JMGO N1 Ultra features an innovative built-in gimbal stand.', features: ['4K UHD Resolution', 'Laser Light Source', '2200 ANSI Lumens', '360-degree Gimbal', 'Auto Focus & Keystone', 'Cloud Gaming Ready'], specifications: { Resolution: '3840 x 2160', Brightness: '2200 ANSI Lumens', Light_Source: 'Triple Color Laser', Throw_Ratio: '0.6:1 - 4.5:1', Speaker: '2 x 10W', Weight: '4.6 kg' }, images: [], stock_status: 'in_stock' },
  // UST Laser TV
  { name: 'Hisense PX2-Pro 4K UST', slug: 'hisense-px2-pro-4k-ust', brand: 'Hisense', category_slug: 'ust-laser-tv', price: 2399.99, short_description: 'Ultra Short Throw 4K laser TV with 120" image from inches away.', description: 'The Hisense PX2-Pro transforms any wall into a massive 120-inch 4K display.', features: ['4K UHD Resolution', 'Ultra Short Throw', '2400+ ANSI Lumens', 'Triple Laser', 'Dolby Vision', 'Ambient Light Rejecting'], specifications: { Resolution: '3840 x 2160', Brightness: '2400 ANSI Lumens', Light_Source: 'Triple Laser', Throw_Ratio: '0.23:1', Screen_Size: '80" - 150"', Speaker: '2 x 15W + Subwoofer', Weight: '14 kg' }, images: [], is_featured: true, stock_status: 'in_stock' },
  { name: 'AWOL Vision LTV-3500 4K', slug: 'awol-vision-ltv-3500-4k', brand: 'AWOL Vision', category_slug: 'ust-laser-tv', price: 5999.99, short_description: 'Premium RGB triple laser UST projector with unmatched brightness.', description: 'The AWOL Vision LTV-3500 is the ultimate ultra-short throw projector.', features: ['4K UHD Resolution', 'RGB Triple Laser', '5500+ ANSI Lumens', '150" Display', 'HDR Support', 'Premium Build'], specifications: { Resolution: '3840 x 2160', Brightness: '5500 ANSI Lumens', Light_Source: 'RGB Triple Laser', Throw_Ratio: '0.198:1', Screen_Size: '80" - 150"', Speaker: '2 x 15W', Weight: '18 kg' }, images: [], is_featured: true, stock_status: 'in_stock' },
  { name: 'Formovie Theater 4K', slug: 'formovie-theater-4k', brand: 'Formovie', category_slug: 'ust-laser-tv', price: 3499.99, short_description: 'Award-winning UST laser projector with ALPD 4.5 technology.', description: 'The Formovie Theater combines ALPD 4.5 laser technology with an ultra-short throw design.', features: ['4K UHD Resolution', 'ALPD 4.5 Laser', '2800+ ANSI Lumens', 'Dolby Vision + HDR10+', '150" Screen', 'Android TV Built-in'], specifications: { Resolution: '3840 x 2160', Brightness: '2800 ANSI Lumens', Light_Source: 'ALPD 4.5', Throw_Ratio: '0.23:1', Screen_Size: '80" - 150"', Speaker: '2 x 15W Dolby Audio', Weight: '12 kg' }, images: [], is_new_arrival: true, stock_status: 'in_stock' },
  { name: 'JMGO U2 4K Laser TV', slug: 'jmgo-u2-4k-laser-tv', brand: 'JMGO', category_slug: 'ust-laser-tv', price: 2199.99, short_description: 'Sleek 4K laser TV with superior optics and smart features.', description: 'The JMGO U2 brings cinematic 4K quality to your living room.', features: ['4K UHD Resolution', 'Laser Light Source', '2400 ANSI Lumens', 'HDR10+', 'Auto Focus', 'Smart OS'], specifications: { Resolution: '3840 x 2160', Brightness: '2400 ANSI Lumens', Light_Source: 'Laser', Throw_Ratio: '0.23:1', Screen_Size: '80" - 130"', Speaker: '2 x 10W', Weight: '8.5 kg' }, images: [], stock_status: 'in_stock' },
  { name: 'Hisense PL1 4K Laser TV', slug: 'hisense-pl1-4k-laser-tv', brand: 'Hisense', category_slug: 'ust-laser-tv', price: 1899.99, short_description: 'Affordable 4K UST laser TV with impressive performance.', description: 'The Hisense PL1 offers 4K ultra-short throw projection at an accessible price.', features: ['4K UHD Resolution', 'Laser Light Source', '2100 ANSI Lumens', 'Ultra Short Throw', 'Smart TV Built-in', 'Voice Control'], specifications: { Resolution: '3840 x 2160', Brightness: '2100 ANSI Lumens', Light_Source: 'Laser', Throw_Ratio: '0.25:1', Screen_Size: '80" - 120"', Speaker: '2 x 10W', Weight: '8 kg' }, images: [], stock_status: 'in_stock' },
  // NOTE: Projector Mounts and Projection Screens categories are empty - products to be added later
];